name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-python
        uses: actions/setup-python@v3
      - name: install pypa/build
        run: pip install build
      - name: build sdist(tarball) and bdist(wheel) to dist/
        run: python -m build .
      - name: publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          # comment the below line to publish to PyPI
          repository_url: https://test.pypi.org/legacy/