name: Testing

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  testing:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
    - uses: actions/checkout@v5
{%- if package_manager == 'poetry' %}
    - name: Install poetry
      run: pipx install poetry
{% elif package_manager == 'uv' %}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
{% endif -%}
{% raw %}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }} {% endraw %}
{%- if package_manager == 'poetry' %}
        cache: poetry
        cache-dependency-path: pyproject.toml
{%- elif package_manager == 'uv' %}
{%- else %}
        cache: pip
        cache-dependency-path: pyproject.toml
{%- endif %}

    - uses: pre-commit/action@v3.0.0
    - name: Install dependencies
      run: {% if package_manager == 'poetry' %}poetry install{% elif package_manager == 'uv' %}uv sync{% else %}pip install ".[dev]"{% endif %}
    - name: Run tests
      run: |
        {% if package_manager == 'uv' %}uv run {% endif %}xonsh -c "xontrib load {{ project_package_name}}"
        {% if package_manager == 'poetry' %}poetry run pytest{% elif package_manager == 'uv' %}uv run pytest{% else %}pytest{% endif %}
