name: Testing

on:
  push:
    branch: main
    tags:
      - 'v*'
  pull_request:

jobs:
  testing:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11-dev"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: 'pyproject.toml'
    - name: Install dependencies
      run: pip install ".[dev]"
    - name: Run tests
      run: pytest
